# Generated by Django 4.1.2 on 2022-11-04 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'ordering': ['name']},
        ),
    ]
