# Generated by Django 4.1.2 on 2022-10-30 05:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('addresses', '0001_initial'),
        ('items', '0001_initial'),
        ('organizations', '0004_alter_organization_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('status', models.CharField(choices=[('active', 'ACTIVE'), ('confirmed', 'CONFIRMED'), ('inactive', 'INACTIVE')], default='inactive', max_length=254, verbose_name='listing status')),
                ('expiry_date', models.CharField(max_length=100)),
                ('collection_time', models.CharField(max_length=254)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('collection_address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='collection_address', to='addresses.address')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item', to='items.item')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization', to='organizations.organization')),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
    ]
