# Generated by Django 4.1.2 on 2022-10-30 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
        ('addresses', '0001_initial'),
        ('organizations', '0004_alter_organization_status'),
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='collection_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='listing', to='addresses.address'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='listing', to='items.item'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='listing', to='organizations.organization'),
        ),
    ]
