# Generated by Django 4.1.2 on 2022-10-31 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_alter_listing_collection_address_alter_listing_item_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='collection_time',
        ),
        migrations.AlterField(
            model_name='listing',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
