# Generated by Django 4.1.2 on 2022-11-03 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_remove_listing_collection_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='amount',
            field=models.CharField(default='1kg', max_length=254, verbose_name='amount'),
            preserve_default=False,
        ),
    ]
