# Generated by Django 4.1.2 on 2022-11-04 14:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_listing_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='collection_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='listing',
            name='timeslot',
            field=models.CharField(choices=[('12am - 2am', '_12AM'), ('2am - 4am', '_2AM'), ('4am - 6am', '_4AM'), ('6am - 8am', '_6AM'), ('8am - 10am', '_8AM'), ('10am - 12pm', '_10AM'), ('12pm - 2pm', '_12PM'), ('2pm - 4pm', '_2PM'), ('4pm - 6pm', '_4PM'), ('6pm - 8pm', '_6PM'), ('8pm - 10pm', '_8PM'), ('10pm - 12am', '_10PM')], default=2001, max_length=254, verbose_name='timeslot option'),
            preserve_default=False,
        ),
    ]
