# Generated by Django 4.1.2 on 2022-10-22 08:54

from django.db import migrations, models
import django.utils.timezone
import organizations.utils
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('website', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, unique=True)),
                ('organization_type', models.CharField(choices=[('Charity', 'CHARITY'), ('Donor', 'DONOR')], default=organizations.utils.OrganizationTypes['DONOR'], max_length=254, verbose_name='organization type')),
                ('status', models.CharField(choices=[('pending', 'PENDING'), ('active', 'ACTIVE'), ('deactivated', 'DEACTIVATED')], default=organizations.utils.OrganizationStatuses['PENDING'], max_length=254, verbose_name='organization status')),
                ('logo_url', models.URLField(default='https://ik.imagekit.io/ipy2x824p/eunoia/placeholders/logo-placeholder_HHrr_N0aM.png', max_length=254)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
    ]
