# Generated by Django 4.1.2 on 2022-10-22 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_created_organizations_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='slug',
            field=models.SlugField(default='default_slug', max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
