# Generated by Django 4.1.2 on 2022-10-24 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_alter_organization_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='logo_id',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
