# Generated by Django 4.1.2 on 2022-10-29 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_added_logo_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='status',
            field=models.CharField(choices=[('pending', 'PENDING'), ('active', 'ACTIVE'), ('deactivated', 'DEACTIVATED')], default='pending', max_length=254, verbose_name='organization status'),
        ),
    ]
