# Generated by Django 4.1.2 on 2022-11-01 03:49

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listings', '0003_remove_listing_collection_time_and_more'),
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart_Listing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('cart', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_listing', to='carts.cart')),
                ('listing', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_listing', to='listings.listing')),
            ],
        ),
    ]
