# Generated by Django 4.1.2 on 2022-10-30 03:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0004_alter_organization_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('item_type', models.CharField(choices=[('Cooked vegetables', 'COOKED_VEGETABLES'), ('Cooked meat', 'COOKED_MEAT'), ('Cooked fish', 'COOKED_FISH'), ('Canned food', 'CANNED_FOOD'), ('Refridgerated food', 'REFRIDGERATED'), ('Diary', 'DIARY'), ('Vegetables', 'VEGETABLES'), ('Meat', 'MEAT'), ('Fish and Seafood', 'FISH_SEAFOOD'), ('Eggs', 'EGGS'), ('Condiments', 'CONDIMENTS'), ('Snacks', 'SNACKS'), ('Oil', 'OIL'), ('Baked goods', 'BAKED_GOODS'), ('Jams and Spreads', 'JAMS_SPREADS'), ('Fruits', 'FRUITS'), ('Beverages', 'BEVERAGES'), ('Rice', 'RICE'), ('Noodles', 'NOODLES'), ('Seasonings', 'SEASONINGS'), ('Pastes and Sauces', 'PASTE_SAUCES'), ('Cutlery', 'CUTLERY'), ('Dried food', 'DRIED_FOOD'), ('Vitamins and Supplements', 'VITAMINS_SUPPLEMENTS'), ('Miscellaneous', 'MISCELLANEOUS')], default='Miscellaneous', max_length=254, verbose_name='item type')),
                ('image_url', models.URLField(default='https://ik.imagekit.io/ipy2x824p/eunoia/placeholders/logo-placeholder_HHrr_N0aM.png', max_length=254)),
                ('image_id', models.CharField(blank=True, max_length=150)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='organizations.organization')),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
    ]
