# Generated by Django 4.1.2 on 2022-10-31 13:33

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listings', '0002_alter_listing_collection_address_alter_listing_item_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timeslot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('date', models.DateField()),
                ('timeslot_option', models.CharField(choices=[('12am - 2am', '_12AM'), ('2am - 4am', '_2AM'), ('4am - 6am', '_4AM'), ('6am - 8am', '_6AM'), ('8am - 10am', '_8AM'), ('10am - 12pm', '_10AM'), ('12pm - 2pm', '_12PM'), ('2pm - 4pm', '_2PM'), ('4pm - 6pm', '_4PM'), ('6pm - 8pm', '_6PM'), ('8pm - 10pm', '_8PM'), ('10pm - 12am', '_10PM')], max_length=254, verbose_name='timeslot option')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listing', to='listings.listing')),
            ],
        ),
    ]
