# Generated by Django 4.1.2 on 2022-11-01 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='charity_ord_id',
            new_name='charity_org_id',
        ),
    ]
