# Generated by Django 4.1.2 on 2022-11-01 10:12

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0002_rename_charity_ord_id_order_charity_org_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order_Listing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('image_url', models.URLField(default='https://ik.imagekit.io/ipy2x824p/eunoia/placeholders/logo-placeholder_HHrr_N0aM.png', max_length=254)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_listing', to='orders.order')),
            ],
        ),
    ]
